name: react-native-android-build-apk
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GITLAB_REPO_URL: ${{ secrets.GITLAB_REPO_URL }}
  WECOM_WEBHOOK_KEY: ${{ secrets.WECOM_WEBHOOK_KEY }}
  UPLOAD_TOKEN_URL: ${{ secrets.UPLOAD_TOKEN_URL }}
  UPLOAD_URL: ${{ secrets.UPLOAD_URL }}
jobs:
  # install-and-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Install npm dependencies
  #       run: |
  #         npm install
  build-android:
    # needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Show commit message
        run: echo $(git log --format=%B -n 1)
      - name: Checkout [dev branch] code
        # if: startsWith( env.commitmsg , 'release(dev)' )
        run: |
          bash ./scripts/checkout.sh "dev"
      - name: Checkout [test branch] code
        if: startsWith( env.commitmsg , 'release(test)' ) || contains(github.event.pull_request.title, 'release(test)' )
        run: |
          bash ./scripts/checkout.sh "test"
      - name: Checkout [master branch] code
        if: startsWith( env.commitmsg , 'release(master)' ) || contains(github.event.pull_request.title, 'release(master)' )
        run: |
          bash ./scripts/checkout.sh "master"
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build Android Release
        run: |
          cd android && chmod +x ./gradlew && ./gradlew assembleRelease
      - name: Send Artifact
        run: |
          node ./scripts/send-file.js
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
