name: react-native-android-build-apk
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GITLAB_REPO_URL: ${{ secrets.GITLAB_REPO_URL }}
jobs:
  # install-and-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Install npm dependencies
  #       run: |
  #         npm install
  build-android:
    # needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GITHUB CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Get commit message
        run: |
          echo ::set-env name=commitmsg::$(git log --format=%B -n 1 ${{ github.event.after }})
      - name: Show commit message
        run: echo $commitmsg
      - name: Checkout [dev branch] code
        if: contains( env.commitmsg , '[dev]' ) || contains(github.event.pull_request.title, '[dev]')
        run: |
          bash ./scripts/checkout.sh -s "dev"
      - name: Checkout [test branch] code
        if: contains( env.commitmsg , '[test]' ) || contains(github.event.pull_request.title, '[test]')
        run: |
          bash ./scripts/checkout.sh -s "test"
      - name: Checkout [master branch] code
        if: contains( env.commitmsg , '[master]' ) || contains(github.event.pull_request.title, '[master]')
        run: |
          bash ./scripts/checkout.sh -s "master"
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build Android Release
        run: |
          cd android && chmod +x ./gradlew && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
