name: build-apk
on:
  push:
    branches:
      - master
env:
  GITLAB_REPO_URL: ${{ secrets.GITLAB_REPO_URL }}
  WECOM_WEBHOOK_KEY: ${{ secrets.WECOM_WEBHOOK_KEY }}
  UPLOAD_TOKEN_URL: ${{ secrets.UPLOAD_TOKEN_URL }}
  UPLOAD_URL: ${{ secrets.UPLOAD_URL }}
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get commit message
        run: |
          GIT_MESSAGE="$(git log --format=%B -n 1)"
          date_str=$(date "+%Y-%m-%d %H:%M:%S")
          seconds=$(date -d "$date_str" +%s)
          seconds_new=$(expr $seconds + 28800) 
          echo "COMMIT_MESSAGE=$GIT_MESSAGE" >> $GITHUB_ENV
          echo "BUILD_TIME=$(date -d @$seconds_new "+%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
      - name: Show commit message
        run: |
          echo "$COMMIT_MESSAGE"
          echo "$BUILD_TIME"
      - name: Checkout  code
        run: |
          bash ./checkout.sh
      # - name: Checkout [dev branch] code
      #   if: startsWith( env.commitmsg , 'release(dev)' )
      #   run: |
      #     bash ./checkout.sh "dev" ${{ env.commitmsg }}
      # - name: Checkout [test branch] code
      #   if: startsWith( env.commitmsg , 'release(test)' ) || contains(github.event.pull_request.title, 'release(test)' )
      #   run: |
      #     bash ./checkout.sh "test"
      # - name: Checkout [master branch] code
      #   if: startsWith( env.commitmsg , 'release(master)' ) || contains(github.event.pull_request.title, 'release(master)' )
      #   run: |
      #     bash ./checkout.sh "master"
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build Android Release
        run: |
          cd android && chmod +x ./gradlew && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
      - name: Send Artifact Success
        run: |
          npm i request
          node ./send-success.js
      - name: Upload Apk & Send message to WeCom Group Chat
        run: |
          node ./scripts/send-file.js
      - name: On Failure
        if: ${{ failure() }}
        run: |
          npm i request
          node ./send-error.js
