name: IOS手动构建
on:
  push:
    branches: [master*]
  pull_request:
    branches: [master*]

  workflow_dispatch:
    inputs:
      buildBranch:
        description: '输入构建分支(dev/test/master/prod)'
        required: true
        default: 'dev'
      uploadArtifact:
        description: '是否将生成的ipa上传到Github Artifact (true/false)'
        required: false
        default: 'true'
      uploadCloud:
        description: '是否将生成的ipa上传到蒲公英。(true/false)'
        required: false
        default: 'true'

env:
  GITLAB_REPO_URL: ${{ secrets.GITLAB_REPO_URL }}
  WECOM_WEBHOOK_KEY: ${{ secrets.WECOM_WEBHOOK_KEY }}
  UPLOAD_TOKEN_URL: ${{ secrets.UPLOAD_TOKEN_URL }}
  UPLOAD_URL: ${{ secrets.UPLOAD_URL }}

jobs:
  build:
    runs-on: macos-10.15
    timeout-minutes: 45
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get commit message
        run: |
          GIT_MESSAGE="$(git log --format=%B -n 1)"
          echo "COMMIT_MESSAGE=$GIT_MESSAGE" >> $GITHUB_ENV
      - name: Show commit message
        run: |
          echo "$COMMIT_MESSAGE"
          echo "$BUILD_TIME"
          echo "${{ github.event.inputs.buildBranch }}"
      - name: Checkout code
        run: |
          bash ./checkout2.sh "${{ github.event.inputs.buildBranch }}"
      - name: Install npm dependencies
        run: |
          npm install
      - name: pod
        run: |
          cd ios && pod install
          cd ..
      - name: Start Build Apk Message
        run: |
          node ./send-startmsg.js "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" "${{ github.event.inputs.uploadCloud }}"  "IOS"

      - uses: yukiarrr/ios-build-action@v1.4.0
        with:
          project-path: ./ios/g_service.xcodeproj
          workspace-path: ./ios/g_service.xcworkspace # optional
          p12-key-base64: ${{ secrets.P12_KEY_BASE64 }}
          p12-cer-base64: ${{ secrets.P12_CER_BASE64 }}
          mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
          team-id: ${{ secrets.TEAM_ID }}
          export-method: 'ad-hoc'
          # export-method: 'development'
          configuration: 'Release'
          output-path: /${{ steps.date.outputs.date }}/${{ github.run_number }}/g-service.ipa
      - name: Upload Artifact Success
        if: ${{ github.event.inputs.uploadArtifact == 'true' }}
        run: |
          npm i request
          node ./send-success.js "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" "${{ github.event.inputs.uploadCloud }}" "IOS"
      - name: push to fir
        id: PushToFir
        run: curl -F file=@/${{ steps.date.outputs.date }}/${{ github.run_number }}/g-service.ipa -F '_api_key=255538ec7cc065061e64e5f01f97278e' https://www.pgyer.com/apiv2/app/upload

      - name: Send finally notify
        run: |
          node ./scripts/send-msg.js "IOS构建成功，并同步到蒲公英平台。\n>Github Job RunId: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} \n>蒲公英地址:[https://www.pgyer.com/****](https://www.pgyer.com/****)"
      - name: On Failure
        if: ${{ failure() }}
        run: |
          node ./send-error.js "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"  "IOS"
